#!/bin/sh

# xinitrc runs automatically when startx is run

xrandr --output eDP-1 --mode 2880x1800 --rate 90

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

exec dwm
