cmap ;cac /home/cole/.cache
cmap ;cfg /home/cole/.config
cmap ;dwn /home/cole/Downloads
cmap ;dt /home/cole/.local/share
cmap ;doc /home/cole/Documents
cmap ;src /home/cole/.local/src
cmap ;vbox /home/cole/VirtualBox
cmap ;cs403 /home/cole/Documents/CS403
cmap ;cs428 /home/cole/Documents/CS428
cmap ;cs438 /home/cole/Documents/CS438
cmap ;cs443 /home/cole/Documents/CS443
